name: material_design_3
description: A new Flutter project.

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NovaSquare-Regular
      fonts:
        - asset: fonts/NovaSquare-Regular.ttf
        - asset: fonts/NovaSquare-Regular.ttf
          weight: 700
    - family: Inter-VariableFont_slnt,wght
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
          style: italic
